[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build]
artifacts = [
    "signals.db",
]

[tool.hatch.version]
path = "src/AudioHaze/__about__.py"

[project]
name = "AudioHaze"
dynamic = ["version"]
authors = [
    { name = "Abdulrahman Shalaby", email = "abdoshalaby.dev@gmail.com" },
    { name = "Abdulrahman El Sharabasy", email = "abdomake@gmail.com" },
]
maintainers = [
    { name = "Abdulrahman Shalaby", email = "abdoshalaby.dev@gmail.com" },
    { name = "Abdulrahman El Sharabasy", email = "abdomake@gmail.com" },
]
description = "This Is A Simple GUI Application To Manipulate Audio Files By Modifying The Audio Wave Form And Display It Using Python"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyttsx3",
    "ttkbootstrap",
    "Pillow",
    "pydub",
    "setuptools",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Win32 (MS Windows)",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
keywords = ["GUI", "Tkinter", "Audio", "App", "Audio Editing", "Audio Processing"]
[project.urls]
homepage = "https://github.com/shalabycr7/AudioHaze"
repository = "https://github.com/shalabycr7/AudioHaze"
changelog = "https://github.com/shalabycr7/AudioHaze/blob/MainDist/CHANGELOG.md"
