[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "AudioHaze"
version = "0.2.1"
authors = [
    { name = "Abdulrahman Shalaby", email = "abdoshalaby.dev@gmail.com" },
]
description = "Simple GUI Application To Manipulate Audio Files By Modifying The Audio Wave Form And Display It Using Python"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = ["numpy==1.24.1", "scipy==1.10.0", "matplotlib==3.6.3", "pyttsx3==2.90", "ttkbootstrap==1.10.1",
    "Pillow==9.4.0", "pydub==0.25.1"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
keywords = ["gui", "audio", "app"]

[project.urls]
"Homepage" = "https://github.com/shalabycr7/AudioHaze"